# Generated by Django 4.2.x — do not edit manually unless you know what you're doing.

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # eventyay's core app provides Event and TeamMember.
        # The exact app_label depends on the host install; 'eventyay' is the
        # canonical label used in the main repo.
        ("eventyay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_settings",
                        to="eventyay.event",
                        verbose_name="Event",
                    ),
                ),
                # ── Video sync ──
                (
                    "video_sync_enabled",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Automatically create and update video rooms when "
                            "Talk sessions are created or modified."
                        ),
                        verbose_name="Enable Talk → Video sync",
                    ),
                ),
                (
                    "inject_speaker_profile",
                    models.BooleanField(
                        default=True,
                        help_text="Show speaker name, bio, and photo inside the video room UI.",
                        verbose_name="Inject speaker profiles into video rooms",
                    ),
                ),
                (
                    "video_sync_mode",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time (on save)"),
                            ("periodic", "Periodic (every 5 min)"),
                            ("manual", "Manual only"),
                        ],
                        default="realtime",
                        max_length=20,
                        verbose_name="Sync mode",
                    ),
                ),
                # ── Ticket gating ──
                (
                    "ticket_gate_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Require a valid ticket purchase to join video rooms.",
                        verbose_name="Gate video access by ticket",
                    ),
                ),
                # ── Navigation visibility ──
                (
                    "show_tickets_in_nav",
                    models.BooleanField(
                        default=True,
                        verbose_name="Show Tickets in public nav",
                    ),
                ),
                (
                    "show_video_in_nav",
                    models.BooleanField(
                        default=True,
                        verbose_name="Show Join Online Video in public nav",
                    ),
                ),
                (
                    "tickets_nav_label",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use default 'Tickets'.",
                        max_length=100,
                        verbose_name="Custom Tickets nav label",
                    ),
                ),
                # ── MC assignment ──
                (
                    "mc_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email MC on room assignment",
                    ),
                ),
                (
                    "mc_permission_level",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("moderate", "Moderate (mute/kick)"),
                            ("host", "Host (full control)"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="MC permission level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integration Settings",
                "verbose_name_plural": "Integration Settings",
            },
        ),
        migrations.CreateModel(
            name="MCAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mc_assignments",
                        to="eventyay.event",
                    ),
                ),
                (
                    "team_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mc_assignments",
                        to="eventyay.teammember",
                        verbose_name="MC",
                    ),
                ),
                (
                    "video_room_id",
                    models.CharField(max_length=200, verbose_name="Video room ID"),
                ),
                (
                    "session_title",
                    models.CharField(blank=True, max_length=300),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "View only"),
                            ("moderate", "Moderate (mute/kick)"),
                            ("host", "Host (full control)"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="Permission level",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Assigned at",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(default=False),
                ),
            ],
            options={
                "verbose_name": "MC Assignment",
                "verbose_name_plural": "MC Assignments",
            },
        ),
        migrations.AddConstraint(
            model_name="mcassignment",
            constraint=models.UniqueConstraint(
                fields=("event", "video_room_id", "team_member"),
                name="unique_mc_per_room",
            ),
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_sync_logs",
                        to="eventyay.event",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        db_index=True,
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                        verbose_name="Level",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=100,
                        verbose_name="Action",
                    ),
                ),
                (
                    "message",
                    models.TextField(verbose_name="Message"),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "video_room_id",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Video room ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "verbose_name_plural": "Sync Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
